//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EClutter.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Area
    {
        public Area()
        {
            this.Items = new HashSet<Item>();
        }

        public int Area_ID { get; set; }
        public string Area_Name { get; set; }
        public int? Edit_Name { get; set; }
        public int Clutter_Count { get; set; }

        public virtual ICollection<Item> Items { get; set; }
    }
}