//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EClutter.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    public partial class Item
    {
        public Item()
        {
            this.Item1 = new HashSet<Item>();
        }

        public int Item_ID { get; set; }

        [Required]
        [StringLength(60, MinimumLength = 3)]
        public string Name { get; set; }

        [Range(0, 8000)]
        public int SpaceTaken { get; set; }

        [StringLength(30, MinimumLength = 2)]
        public string Location { get; set; }

        public int Moved { get; set; }
        public string CoverImage { get; set; }
        public bool Sell { get; set; }
        public bool Dispose { get; set; }
        public bool Repurpose { get; set; }
        public bool GiveAway { get; set; }

        public bool ActionCompleted { get; set; }
        public int SubItem { get; set; }
        public int Area_ID { get; set; }

        public string ClassActions { get; set; }

        public virtual Area Area { get; set; }
        public virtual ICollection<Item> Item1 { get; set; }
        public virtual Item Item2 { get; set; }


        //Counts For Chart
        public int ForSale { get; set; }
        public int ForDisposal { get; set; }
        public int ForRepurposing { get; set; }
        public int ForGivingAway { get; set; }

        public int Sold { get; set; }
        public int Disposed { get; set; }
        public int Repurposed { get; set; }
        public int GivenAway { get; set; }

        public int AmountCompleted;
        public int AmountNotCompleted;

    }
}

